# Generated by Django 4.1.7 on 2023-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bastaush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='elementary/')),
            ],
            options={
                'verbose_name': 'Учитель начальной школы',
                'verbose_name_plural': 'Учителя начальной школы',
            },
        ),
    ]
